name: gettsim

dependencies:
  - python=3.7
  - numpy
  - sphinx
  - pandas=0.24.2
  - statsmodels
  - pytest
  - pytest-xdist
  - scipy
  - matplotlib
  - pytest-cov
  - jupyter
  - numba
  - mpmath
  - pip
  - xlrd
  - seaborn
  - pip:
      - pre-commit
      - termcolor
